// Shared script for Tinnitus Therapy Suite persistence
// Include this at the bottom of therapy pages to handle auto-save/load

/** 
 * Helpers for consistent localStorage interaction
 * Initialized at the top to ensure availability for immediate-run IIFEs.
 */
let _memStorage = {};
let _memSessionActive = false;

const isStorageAvailable = () => {
    try { localStorage.setItem('tts_t', '1'); localStorage.removeItem('tts_t'); return true; } 
    catch (e) { return false; }
};

const _safeGet = (k) => { try { return localStorage.getItem(k); } catch(e) { return _memStorage[k]; } };
const _safeSet = (k, v) => { try { localStorage.setItem(k, v); } catch(e) { _memStorage[k] = v; } };

const getJson = (key, defaultVal = []) => {
    const val = _safeGet('tts_' + key);
    try { return val ? JSON.parse(val) : defaultVal; } catch (e) { return defaultVal; }
};
const setJson = (key, val) => _safeSet('tts_' + key, JSON.stringify(val));

const loadSetting = (key, defaultVal) => _safeGet('tts_' + key) || defaultVal;
const saveSetting = (key, val) => _safeSet('tts_' + key, val);

const getTodayKey = () => new Date().toISOString().split('T')[0];

/**
 * Session Authorization
 * Marks the onboarding as complete and authorizes the current session.
 */
function completeOnboarding() {
    try {
        saveSetting('onboarding_step', '1');
        saveSetting('last_seen_version', APP_VERSION);
        try { sessionStorage.setItem('tts_session_active', 'true'); } catch(e) {}
        _memSessionActive = true;
    } catch (e) { console.error("TTS: Failed to save onboarding state.", e); }
    console.log("TTS: Onboarding completed.");
}

/**
 * Estimates the current usage of localStorage for the origin.
 * Returns usage in KB.
 */
function getLocalStorageUsage() {
    let total = 0;
    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        const value = localStorage.getItem(key);
        // Estimate size: key length + value length (each char is 2 bytes in JS strings)
        total += key.length + value.length;
    }
    return (total / 1024).toFixed(2); // Convert bytes to KB
}
window.getLocalStorageUsage = getLocalStorageUsage;

/**
 * Core Settings Actions
 * Attached to window for global access from UI buttons.
 */

/**
 * Requests that the browser treat the storage for this origin as persistent.
 * This makes it significantly less likely that your API key or logs will be 
 * cleared automatically by the browser during storage maintenance.
 */
async function requestPersistentStorage() {
    if (navigator.storage && navigator.storage.persist) {
        try {
            const isPersisted = await navigator.storage.persist();
            if (isPersisted) {
                console.log("TTS: Persistent storage granted.");
            } else {
                console.warn("TTS: Persistent storage denied. Data may be cleared if device storage is low.");
            }
        } catch (e) {
            console.error("TTS: Error requesting persistence:", e);
        }
    }
}
requestPersistentStorage();

// Import the Google Generative AI SDK (ensure it's loaded in your HTML, e.g., via <script src="...">)
// This line assumes the SDK is available globally (e.g., from a CDN script tag).
// If you were using a module bundler, you'd use: import { GoogleGenerativeAI } from "@google/generative-ai";
const APP_VERSION = "2.3.3";

let MAINTENANCE_MODE = false; // Default to OPEN; only close if maintenance.json says so

let activeSessionKey = null; // Tracks the unlocked key for the current session

// ⚠️ CRITICAL SECURITY WARNING ⚠️
// DIRECTLY INCLUDING YOUR GEMINI API KEY IN CLIENT-SIDE CODE IS UNSAFE FOR PRODUCTION.
// THIS KEY WILL BE PUBLICLY VISIBLE TO ANYONE INSPECTING YOUR BROWSER'S SOURCE CODE.
// USE A SECURE SERVER-SIDE PROXY FOR PRODUCTION DEPLOYMENTS.
const HARDCODED_KEY = "YOUR_ACTUAL_API_KEY_HERE"; 

/**
 * Manages state and interactions for the Google Gemini AI integration.
 * Encapsulates the API key, model initialization, and specific therapeutic helpers.
 */
class TinnitusAIManager {
    constructor() {
        this.genAI = null;
        this.decryptedKey = null;
        this.disclaimer = "Medical Disclaimer: This suggestion is generated by AI (Gemini) for educational purposes. It is not a substitute for professional medical advice, diagnosis, or treatment.";
        this.modelName = "gemini-pro";
    }

    /**
     * Robustly resolves the GoogleGenerativeAI class from various global namespaces.
     */
    _getSDK() {
        try {
            // More exhaustive search for the Google AI SDK global across different CDN formats
            let SDK = window.GoogleGenerativeAI ||
                      (window.google && (window.google.generativeai || window.google.generativeAi || {}).GoogleGenerativeAI) ||
                      (window.google && (window.google.generativeai || window.google.generativeAi)) ||
                      window.GenerativeAI;

            if (SDK && typeof SDK !== 'function' && SDK.GoogleGenerativeAI) SDK = SDK.GoogleGenerativeAI;
            if (SDK && SDK.default) SDK = SDK.default;

            return (typeof SDK === 'function') ? SDK : null;
        } catch (e) {
            console.error("TTS: Error resolving AI SDK:", e);
            return null;
        }
    }

    /**
     * Initializes the Generative AI SDK with the provided or hardcoded key.
     */
    init(key = null) {
        if (key) {
            this.decryptedKey = key;
            // Sync back to session variable for cross-module availability
            activeSessionKey = key;
            try { sessionStorage.setItem('tts_gemini_key_session', key); } catch(e) {}
        } else {
            // Attempt to load from session memory (variable or sessionStorage) or plain-text storage
            this.decryptedKey = activeSessionKey || 
                                (function() { try { return sessionStorage.getItem('tts_gemini_key_session'); } catch(e) { return null; } })() || 
                                loadSetting('gemini_api_key', null);
            
            if (this.decryptedKey) activeSessionKey = this.decryptedKey;
        }

        const activeKey = this.decryptedKey || HARDCODED_KEY;
        const SDK = this._getSDK();

        try {
            if (SDK && activeKey && activeKey !== HARDCODED_KEY && activeKey !== "ENCRYPTED_KEY_LOCKED") {
                this.genAI = new SDK(activeKey);
            } else {
                this.genAI = null;
            }
        } catch (e) {
            console.warn("AI Initialization failed: Check API Key or SDK availability.");
            this.genAI = null;
        }
    }

    /**
     * Performs a connectivity test to verify the API key is working.
     */
    async performTest() {
        // Self-heal: Attempt to re-prime the engine in case the SDK loaded late
        if (!this.genAI) this.init();

        const SDK = this._getSDK();

        if (!SDK) {
            const scriptTag = document.querySelector('script[src*="generative-ai"]');
            let diag = "Global variable not found.";
            if (!scriptTag) diag = "SDK script tag missing from HTML.";
            else diag = "Script tag present but failed to define globals (check browser console).";
            
            return { success: false, message: `AI SDK failed to load (${diag}). Check connection or disable ad-blockers (allow unpkg.com and cdn.jsdelivr.net).` };
        }
        
        if (!this.genAI || !this.decryptedKey || this.decryptedKey === "YOUR_ACTUAL_API_KEY_HERE") {
            return { success: false, message: "AI Engine not initialized. Please provide a valid API key from Google AI Studio." };
        }
        
        try {
            const model = this.genAI.getGenerativeModel({ model: this.modelName });
            const result = await model.generateContent("Test connection: hello");
            const response = await result.response;
            const text = response.text();
            return text ? { success: true, message: "Connection successful! Gemini responded." } 
                        : { success: false, message: "Connection successful, but Gemini gave an empty response." };
        } catch (error) {
            console.error("Gemini test connection error:", error);
            let errorMessage = "Connection failed. ";
            if (error.message.includes("API key not valid")) {
                errorMessage += "Invalid API key. Please check your key.";
            } else if (error.message.includes("blocked due to SAFETY")) {
                errorMessage += "Gemini blocked the test prompt due to safety concerns. Try a different test.";
            } else if (error.message.includes("rate limit")) {
                errorMessage += "Rate limit exceeded. Try again later.";
            } else {
                errorMessage += `Error: ${error.message}`;
            }
            return { success: false, message: errorMessage };
        }
    }

    /**
     * Centralized method to handle AI requests with safety settings and disclaimers.
     */
    async fetchAIAssistance(taskType, payload) {
        // Self-healing: try to re-init if genAI is missing (e.g. SDK loaded late or navigation reset)
        if (!this.genAI) {
            this.init();
        }

        if (!this.genAI) {
            return "AI Features are currently unconfigured. Please check the suite's setup instructions to enable Gemini assistance.";
        }
        try {
            const model = this.genAI.getGenerativeModel({ 
                model: this.modelName,
                safetySettings: [
                    { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
                    { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
                    { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
                    { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
                ]
            });
            const chat = model.startChat({
                history: [{ role: "user", parts: [{ text: JSON.stringify(payload.system_instruction) }] }],
                generationConfig: { maxOutputTokens: 200 },
            });
            const result = await chat.sendMessage(JSON.stringify(payload.input));
            const responseText = result.response.text();
            return `${responseText}\n\n<i>${this.disclaimer}</i>`;
        } catch (error) {
            console.error(`AI Integration Error [${taskType}]:`, error);
            return "Could not connect to the AI assistant. Please try again later.";
        }
    }

    async getBalancedThoughtSuggestion(automaticThought) {
        const prompt = {
            system_instruction: "You are a specialized CBT assistant for tinnitus habituation. Help the user reframe their 'Automatic Thought' into a 'Balanced Thought' based on Tinnitus Retraining Therapy principles. Keep it brief, supportive, and non-clinical.",
            input: automaticThought
        };
        return await this.fetchAIAssistance("cbt_reframing", prompt);
    }

    async getSOSSupport(userInput = "I am having a spike right now.") {
        const latestDistress = getLatestLogData('distress_log');
        const context = latestDistress ? `[Context: User's latest distress score is ${latestDistress.data}/100 recorded on ${latestDistress.date}] ` : "";

        const prompt = {
            system_instruction: "You are a specialized tinnitus crisis counselor. The user is experiencing a 'spike'. Provide immediate CBT reframing, reassure them that spikes are temporary, and suggest a 2-minute breathing focus.",
            input: context + userInput
        };
        return await this.fetchAIAssistance("sos_support", prompt);
    }

    async getSoundRecipe(description) {
        const prompt = {
            system_instruction: "You are a sound therapy expert. Based on the user's description of their tinnitus suggest a 'Sound Recipe' using noise colors and nature sounds.",
            input: description
        };
        return await this.fetchAIAssistance("sound_recipe", prompt);
    }

    async getPatternAnalysis(userQuery = "") {
        const anonymizedHistory = {
            usage_patterns: getJson('usage_log', {}),
            distress_history: getJson('distress_log', {}),
            reports_sleep_issues: loadSetting('reports_sleep_issues', 'false') === 'true',
            recent_situational_contexts: getThoughtRecords().slice(-5).map(tr => ({
                date: new Date(tr.timestamp).toLocaleDateString(),
                situation: tr.situation,
                emotions: tr.emotions
            }))
        };
        const prompt = {
            system_instruction: "Identify potential correlations in therapy logs, reported sleep issues, and situational data. State clearly that these are correlations and suggest one focus area for next week.",
            input: { user_question: userQuery, anonymized_data: anonymizedHistory }
        };
        return await this.fetchAIAssistance("pattern_finder", prompt);
    }

    async getTRTExplanation(question) {
        const prompt = {
            system_instruction: "You are a TRT coach. Explain concepts like habituation and neuroplasticity in supportive, everyday language.",
            input: question
        };
        return await this.fetchAIAssistance("trt_coach", prompt);
    }

    async getClinicalSummary() {
        const reportData = getClinicalReportData("AI Summary Generation", {}, {});
        const prompt = {
            system_instruction: "Summarize the user's progress for an audiologist focus on trends in distress, adherence, and reported sleep issues. Write one professional paragraph.",
            input: { 
                distress: reportData.psychological.lastTHIScore, 
                usage: reportData.usage.todayMinutes,
                reports_sleep_issues: loadSetting('reports_sleep_issues', 'false') === 'true'
            }
        };
        return await this.fetchAIAssistance("clinical_summary", prompt);
    }

    async getDailyMotivation() {
        const prompt = {
            system_instruction: "Find one 'win' in usage/distress trends and provide a short motivational boost.",
            input: { usage: getJson('usage_log', {}), distress: getJson('distress_log', {}) }
        };
        return await this.fetchAIAssistance("daily_coach", prompt);
    }

    async getEnvironmentalAdvice(dbLevel, floorStatus) {
        const prompt = {
            system_instruction: "Provide one tip on whether this environment is ideal for tinnitus habituation based on noise levels.",
            input: { db_level: dbLevel, status: floorStatus }
        };
        return await this.fetchAIAssistance("environmental_advice", prompt);
    }

    async getMindfulnessScript(thought) {
        const prompt = {
            system_instruction: "Generate a custom 1-minute mindfulness script designed to help a user detach from this specific thought.",
            input: thought
        };
        return await this.fetchAIAssistance("mindfulness_script", prompt);
    }

    async getHabituationForecast() {
        const data = Object.entries(getDistressScores()).map(([date, score]) => ({ date, score }));
        if (data.length < 3) return "Insufficient data for a forecast.";
        const prompt = {
            system_instruction: "Predict future habituation progress and provide one tip based on distress trends and reported sleep issues. State this is an AI projection.",
            input: { 
                thi_history: data, 
                reports_sleep_issues: loadSetting('reports_sleep_issues', 'false') === 'true'
            }
        };
        return await this.fetchAIAssistance("habituation_forecast", prompt);
    }

    async getPersonalizedInsights() {
        const report = getClinicalReportData("Insight Generation", {}, {});
        const prompt = {
            system_instruction: "Analyze the data for positive trends and consider reported sleep issues. Provide one paragraph of encouragement and one actionable tip.",
            input: { 
                thi: report.psychological.lastTHIScore, 
                usage: report.usage, 
                ri: report.ri.latestRIResult,
                reports_sleep_issues: loadSetting('reports_sleep_issues', 'false') === 'true'
            }
        };
        return await this.fetchAIAssistance("progress_insights", prompt);
    }
}


/**
 * Derives a cryptographic key from a PIN using PBKDF2.
 * @param {string} pin - The user's PIN.
 * @param {Uint8Array} salt - A random salt.
 * @returns {Promise<CryptoKey>} The derived AES-GCM key.
 */
async function deriveKeyFromPin(pin, salt) {
    const enc = new TextEncoder();
    const keyMaterial = await crypto.subtle.importKey(
        "raw",
        enc.encode(pin),
        { name: "PBKDF2" },
        false,
        ["deriveBits", "deriveKey"]
    );
    return crypto.subtle.deriveKey(
        {
            name: "PBKDF2",
            salt: salt,
            iterations: 100000, // High iteration count for security
            hash: "SHA-256",
        },
        keyMaterial,
        { name: "AES-GCM", length: 256 },
        true,
        ["encrypt", "decrypt"]
    );
}

/**
 * Encrypts the Gemini API key using AES-GCM.
 * @param {string} apiKey - The plain text Gemini API key.
 * @param {string} pin - The user's PIN.
 * @returns {Promise<{pinPath: object, rcPath: object, recoveryCode: string}>}
 */
async function encryptGeminiKey(apiKey, pin) {
    // Generate a 16-character hexadecimal recovery code
    const recoveryCode = Array.from(crypto.getRandomValues(new Uint8Array(8)), b => b.toString(16).padStart(2, '0')).join('').toUpperCase();
    const enc = new TextEncoder();
    const encodedKey = enc.encode(apiKey);

    async function _encryptWithSecret(secret) {
        const salt = crypto.getRandomValues(new Uint8Array(16));
        const iv = crypto.getRandomValues(new Uint8Array(12));
        const cryptoKey = await deriveKeyFromPin(secret, salt);
        const encrypted = await crypto.subtle.encrypt({ name: "AES-GCM", iv: iv }, cryptoKey, encodedKey);
        return {
            encryptedKey: btoa(String.fromCharCode(...new Uint8Array(encrypted))),
            salt: btoa(String.fromCharCode(...salt)),
            iv: btoa(String.fromCharCode(...iv))
        };
    }

    const pinPath = await _encryptWithSecret(pin);
    const rcPath = await _encryptWithSecret(recoveryCode);

    return {
        pinPath,
        rcPath,
        recoveryCode
    };
}

/**
 * Decrypts the Gemini API key using AES-GCM.
 * @param {string} input - The user's PIN or Recovery Code.
 * @returns {Promise<string|null>} The decrypted API key or null if decryption fails.
 */
async function decryptGeminiKey(input) {
    // Attempt path 1: The Standard PIN
    let key = await _attemptDecrypt(input, 'gemini_api_key_encrypted', 'gemini_api_key_salt', 'gemini_api_key_iv');
    if (key) {
        activeSessionKey = key;
        tinnitusAI.init(key);
        return key;
    }

    // Attempt path 2: The Recovery Code
    key = await _attemptDecrypt(input, 'gemini_api_key_rc_encrypted', 'gemini_api_key_rc_salt', 'gemini_api_key_rc_iv');
    if (key) {
        activeSessionKey = key;
        tinnitusAI.init(key);
        return key;
    }

    return null;
}

async function _attemptDecrypt(secret, keySet, saltSet, ivSet) {
    const encKey = loadSetting(keySet, null);
    const salt = loadSetting(saltSet, null);
    const iv = loadSetting(ivSet, null);
    if (!encKey || !salt || !iv) return null;

    try {
        const decodedEncKey = Uint8Array.from(atob(encKey), c => c.charCodeAt(0));
        const decodedSalt = Uint8Array.from(atob(salt), c => c.charCodeAt(0));
        const decodedIv = Uint8Array.from(atob(iv), c => c.charCodeAt(0));
        const cryptoKey = await deriveKeyFromPin(secret, decodedSalt);
        const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: decodedIv }, cryptoKey, decodedEncKey);
        return new TextDecoder().decode(decrypted);
    } catch (e) {
        return null;
    }
}

/**
 * Resets the application onboarding status and session.
 */
function resetOnboarding() {
    // Clear all keys prefixed with tts_ to ensure a true clean slate
    try {
        const keysToRemove = [];
        for (let i = 0; i < localStorage.length; i++) {
            const key = localStorage.key(i);
            if (key && key.startsWith('tts_')) keysToRemove.push(key);
        }
        keysToRemove.forEach(k => localStorage.removeItem(k));
    } catch(e) {}
    
    _memStorage = {};
    _memSessionActive = false;
    
    // Clear session storage as well to reset session-bound gatekeeper states
    sessionStorage.clear();

    alert("System reset successful. Redirecting to welcome screen...");
    // Force navigation to the base index.html without any query parameters
    window.location.href = window.location.pathname.replace('index.html', '') + 'index.html';
}
window.resetOnboarding = resetOnboarding;

/**
 * Retrieves the most recent entry from a JSON-based log.
 * @param {string} logKey - The key (without tts_ prefix) for the log.
 * @returns {object|null} The latest entry or null.
 */
function getLatestLogData(logKey) {
    const log = getJson(logKey, {});
    const dates = Object.keys(log).sort();
    if (dates.length === 0) return null;
    const latestDate = dates[dates.length - 1];
    return { date: latestDate, data: log[latestDate] };
}

function getThoughtRecords() { return getJson('thought_records', []); }
function getDistressScores() { return getJson('distress_log', {}); }
function getDailyUsage() {
    const log = getJson('usage_log', {});
    return log[getTodayKey()] || 0;
}

function logDistressScore(score) {
    const log = getJson('distress_log', {});
    log[getTodayKey()] = score;
    setJson('distress_log', log);
}

function logUsageMinutes(mins) {
    const log = getJson('usage_log', {});
    const today = getTodayKey();
    log[today] = (log[today] || 0) + mins;
    setJson('usage_log', log);
}

function logRIResult(seconds) {
    const log = getJson('ri_log', {});
    const today = getTodayKey();
    if (!log[today]) log[today] = [];
    log[today].push(seconds);
    setJson('ri_log', log);
}

function logTMCPoint(freq, level) {
    const log = getJson('tmc_log', {});
    log[freq] = level;
    setJson('tmc_log', log);
}

function logQFactor(qFactor) {
    const log = getJson('q_factor_log', {});
    log[getTodayKey()] = qFactor;
    setJson('q_factor_log', log);
}

function logLoudnessGrowthPoint(freq, obj, subj) {
    const log = getJson('lg_log', {});
    const today = getTodayKey();
    if (!log[today]) log[today] = [];
    log[today].push({ freq, obj, subj });
    setJson('lg_log', log);
}

function logThoughtRecordEntry(entry) {
    const records = getThoughtRecords();
    records.push({ ...entry, timestamp: new Date().toISOString() });
    setJson('thought_records', records);
}

function resetModuleSettings(prefixArray) {
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith('tts_')) {
            const settingKey = key.replace('tts_', '');
            if (prefixArray.some(p => settingKey.startsWith(p))) {
                keysToRemove.push(key);
            }
        }
    }
    keysToRemove.forEach(k => localStorage.removeItem(k));
    alert("Settings reset. Reloading module...");
    window.location.reload();
}

// Pre-fetch system voices to ensure they are indexed by the browser for the narrator
if (typeof speechSynthesis !== 'undefined') {
    speechSynthesis.getVoices();
}

/**
 * Retrieves a unified validation status object covering engine, phase, and DSP tests.
 */
function getUnifiedValidationStatus() {
    const engineResults = loadSetting('engine_validation_results', 'Not Performed');
    const phaseStatus = loadSetting('phase_status', 'Not Verified');
    const dspStatus = window.lastValidationStatus || 'Not Performed';
    const lastValidationDate = loadSetting('last_validation_date', null);

    const recommendations = [];
    let isValid = true;

    // Check expiration (30 days)
    if (lastValidationDate) {
        const diff = Date.now() - new Date(lastValidationDate).getTime();
        if (diff > (30 * 24 * 60 * 60 * 1000)) {
            isValid = false;
            recommendations.push("- Your system validation has expired (older than 30 days). Please re-run System Validation.");
        }
    } else {
        isValid = false;
    }

    if (engineResults === 'Not Performed' || engineResults.includes('[FAIL]')) {
        isValid = false;
        recommendations.push("- Automated Engine Validation is missing or failed. Please run the 'System Validation' tool on the home page.");
    }
    
    if (phaseStatus === 'Not Verified') {
        isValid = false;
        recommendations.push("- Hardware Phase is unverified. Use the 'Phase Test' in System Validation to confirm headphone wiring.");
    } else if (phaseStatus.includes('Error')) {
        isValid = false;
        recommendations.push("- Phase error detected. Check for loose connections or virtual surround sound software.");
    }

    if (dspStatus.includes('FAIL')) {
        isValid = false;
        if (dspStatus.includes('Shallow Notch')) recommendations.push("- Shallow Notch failure: Clinical research targets >40dB attenuation. Disable any audio 'enhancer' or 'booster' browser extensions.");
        if (dspStatus.includes('Frequency Mismatch')) recommendations.push("- Frequency mismatch failure: Ensure your OS audio settings are set to 44.1kHz or 48kHz and restart your browser.");
        if (dspStatus.includes('Cross-over')) recommendations.push("- Filter Cross-over failure: The Low-Cut frequency must be lower than the High-Cut frequency. Adjust your filter sliders.");
    }

    return {
        engine: engineResults,
        phase: phaseStatus,
        dsp: dspStatus,
        isValid: isValid,
        lastDate: lastValidationDate,
        recommendations: recommendations
    };
}

/**
 * NoiseGenerator handles the procedural generation of calibrated noise colors.
 * Includes peak volume normalization to ensure consistent therapeutic output levels.
 */
class NoiseGenerator {
    constructor(ctx) {
        // Robust verification of the AudioContext before initialization
        const isValidCtx = ctx && typeof ctx.createBuffer === 'function' && typeof ctx.sampleRate === 'number';
        this.ctx = isValidCtx ? ctx : null;
        this._workletLoading = null; // Singleton tracker for addModule
    }

    /**
     * Normalizes the peak amplitude of buffer data to a target level.
     * This prevents digital clipping while maintaining a high signal-to-noise ratio.
     */
    _normalize(data, targetPeak = 0.9) {
        if (!data || data.length === 0) return;
        let max = 0;
        for (let i = 0; i < data.length; i++) {
            const abs = Math.abs(data[i]);
            if (abs > max) max = abs;
        }
        if (max > 0) {
            const ratio = targetPeak / max;
            for (let i = 0; i < data.length; i++) {
                data[i] *= ratio;
            }
        }
    }

    /**
     * Generates an AudioBuffer for the requested color.
     * Consolidates generation logic to ensure consistent spectra across modules.
     */
    generate(color, bufferSize = null) {
        if (!this.ctx) {
            console.warn("NoiseGenerator: Invalid or missing AudioContext. Audio generation aborted.");
            return null;
        }

        const targetColor = (color || 'white').toLowerCase().trim().replace(/(_noise| noise)/g, '');
        const sampleRate = this.ctx.sampleRate;
        
        // Ensure bufferSize is valid; fallback to 2 seconds of audio
        const size = (typeof bufferSize === 'number' && bufferSize > 0) ? bufferSize : sampleRate * 2;
        
        let buffer;
        try {
            buffer = this.ctx.createBuffer(1, size, sampleRate);
        } catch (e) {
            console.error("NoiseGenerator: Failed to create AudioBuffer. Check memory or sample rate.", e);
            return null;
        }
        
        const d = buffer.getChannelData(0);
        const sr = this.ctx.sampleRate;
        const ratio = 44100 / sr;

        // Scaled Paul Kellet Filter Bank
        const poles = [0.99886, 0.99332, 0.96900, 0.86870, 0.55000, -0.76160];
        const gains = [0.0555179, 0.0750759, 0.1538520, 0.3104856, 0.5329522, -0.0168980];
        const p = poles.map(val => Math.pow(Math.abs(val), ratio) * Math.sign(val));
        const g = gains.map((val, i) => val * (1 - Math.abs(p[i])) / (1 - Math.abs(poles[i])));

        // Scaled Brown Lossy Integrator
        const brP = Math.pow(1 / 1.02, ratio);
        const brG = (1 - brP) * 50;

        switch (targetColor) {
            case 'white': {
                for (let i = 0; i < size; i++) d[i] = Math.random() * 2 - 1;
                break;
            }
            case 'pink': {
                let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
                for (let i = 0; i < size; i++) {
                    const w = Math.random() * 2 - 1;
                    b0 = p[0] * b0 + w * g[0]; b1 = p[1] * b1 + w * g[1]; b2 = p[2] * b2 + w * g[2];
                    b3 = p[3] * b3 + w * g[3]; b4 = p[4] * b4 + w * g[4]; b5 = p[5] * b5 + w * g[5];
                    d[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + w * .5362) * .11; b6 = w * .115926;
                }
                break;
            }
            case 'blue': {
                let lastB = 0;
                for (let i = 0; i < size; i++) { const w = Math.random() * 2 - 1; d[i] = (w - 0.5 * lastB) * 0.7; lastB = w; }
                break;
            }
            case 'violet': {
                let lastV = 0;
                for (let i = 0; i < size; i++) { const w = Math.random() * 2 - 1; d[i] = w - lastV; lastV = w; }
                break;
            }
            case 'brown': {
                let lastBr = 0;
                for (let i = 0; i < size; i++) { const w = Math.random() * 2 - 1; d[i] = (lastBr * brP) + (w * brG); lastBr = d[i]; }
                break;
            }
            default: {
                // Default to white noise if color is unsupported
                for (let i = 0; i < size; i++) d[i] = Math.random() * 2 - 1;
            }
        }

        this._normalize(d);
        return buffer;
    }

    /**
     * Attempts to create an AudioWorkletNode for real-time noise generation.
     * Falls back to a looped AudioBufferSourceNode if noise-processor.js is missing
     * or if the browser does not support AudioWorklets.
     * 
     * @param {string} color - The noise color (e.g., 'white', 'pink', 'brown').
maint     * @param {object} options - Configuration options (loop, bufferSize).
     * @returns {Promise<AudioNode|null>} An active noise node or null.
     */
    async createSafeNoiseNode(color, options = {}) {
        const { loop = true, bufferSize = null } = options;
        if (!this.ctx) return null;

        // 1. Try AudioWorklet (Modern standard, low latency)
        if (this.ctx.audioWorklet) {
            try {
                // Ensure we only attempt to add the module once per context
                if (!this._workletLoading) {
                    this._workletLoading = this.ctx.audioWorklet.addModule('./noise-processor.js');
                }
                await this._workletLoading;

                const node = new AudioWorkletNode(this.ctx, 'noise-processor', {
                    processorOptions: { color: color || 'white' }
                });

                // Listen for internal DSP health reports from the audio thread
                node.port.onmessage = (event) => {
                    if (event.data.type === 'DSP_WARNING') {
                        logTherapyError('AudioWorklet', event.data.message, { color, sampleRate: this.ctx.sampleRate });
                    } else if (event.data.type === 'DSP_METRIC') {
                        // Audit high load events (>80% budget) for clinical review
                        if (!event.data.isStable) {
                            console.warn(`[AudioEngine] High CPU Load: ${event.data.load}% at ${event.data.sampleRate}Hz`);
                            logTherapyError('Performance', `High DSP Load: ${event.data.load}%`, { color, sampleRate: event.data.sampleRate });
                        }
                    }
                };

                // Compatibility shim: AudioWorkletNodes don't have .start()/.stop().
                // We add no-ops so therapy modules can call them without checking node types.
                if (typeof node.start !== 'function') node.start = () => {};
                if (typeof node.stop !== 'function') node.stop = () => {};

                return node;
            } catch (e) {
                console.warn("NoiseGenerator: AudioWorklet failed (noise-processor.js may be missing). Falling back to pre-rendered buffer.", e);
            }
        }

        // 2. Fallback: Pre-rendered AudioBufferSourceNode
        const buffer = this.generate(color, bufferSize);
        if (!buffer) return null;

        const source = this.ctx.createBufferSource();
        source.buffer = buffer;
        source.loop = loop;
        // Note: The caller must still call .start() on the returned source node.
        return source;
    }
}

/** Compatibility wrapper for legacy procedural calls */
function createTrahregNoise(ctx, color, bufferSize) {
    return new NoiseGenerator(ctx).generate(color, bufferSize);
}

/**
 * Retrieves list of audio devices.
 */
async function getAudioDevices() {
    if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
        return { inputs: [], outputs: [] };
    }
    const devices = await navigator.mediaDevices.enumerateDevices();
    return {
        inputs: devices.filter(d => d.kind === 'audioinput'),
        outputs: devices.filter(d => d.kind === 'audiooutput')
    };
}

/**
 * Context-aware logger for technical and clinical auditing.
 * Saves exceptions to origin-private storage for clinical review.
 */
function logTherapyError(module, error, context = {}) {
    const errorLog = getJson('error_log', []);
    const entry = {
        timestamp: new Date().toISOString(),
        module,
        message: error.message || error,
        context: {
            ...context,
            userAgent: navigator.userAgent,
            appVersion: APP_VERSION,
            sampleRate: (window.AudioContext || window.webkitAudioContext) ? 'Active' : 'N/A'
        }
    };
    errorLog.push(entry);
    if (errorLog.length > 25) errorLog.shift(); // Keep logs lean
    setJson('error_log', errorLog);
    console.error(`[Therapy Engine Error: ${module}]`, error);
}

function getTherapyErrorLog() { return getJson('error_log', []); }

/**
 * Validates if a frequency is within safe bounds for the current audio context.
 */
function isFrequencySafe(ctx, freq) {
    if (!ctx || isNaN(freq)) return false;
    const nyquist = ctx.sampleRate / 2;
    // Stay 5% away from Nyquist to prevent aliasing/filter instability
    return freq > 20 && freq < (nyquist * 0.95);
}

function exportAllData() {
    const data = {};
    for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key.startsWith('tts_')) {
            data[key] = localStorage.getItem(key);
        }
    }
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `trahreg_tinnitus_backup_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
}

function importAllData(file) {
    const reader = new FileReader();
    reader.onload = (e) => {
        try {
            const data = JSON.parse(e.target.result);
            Object.keys(data).forEach(key => {
                if (key.startsWith('tts_')) localStorage.setItem(key, data[key]);
            });
            alert("Data imported successfully. Reloading...");
            window.location.reload();
        } catch (err) {
            alert("Error importing data. Ensure the file is a valid backup.");
        }
    };
    reader.readAsText(file);
}

function getClinicalReportData(modeName, settingsObj, techSpecsObj = {}) {
    const validation = getUnifiedValidationStatus();
    const usage = getDailyUsage();

    // Consolidate latest data retrieval using the new helper
    const latestMML = getLatestLogData('mml_log');
    let mmlSummary = "N/A";
    if (latestMML) {
        const mmlVal = Array.isArray(latestMML.data) ? latestMML.data.slice(-1)[0] : latestMML.data;
        mmlSummary = `Latest MML: ${mmlVal}%`;
    }

    const latestLG = getLatestLogData('lg_log');
    let latestLGSummary = "N/A";
    if (latestLG && latestLG.data) {
        const points = Array.isArray(latestLG.data) ? latestLG.data.length : 1;
        latestLGSummary = `Points: ${points}`;
    }

    const latestQF = getLatestLogData('q_factor_log');
    const latestQFactor = (latestQF && latestQF.data) ? latestQF.data : "N/A";

    const latestRI = getLatestLogData('ri_log');
    let riSummary = "N/A";
    if (latestRI) {
        const riVal = Array.isArray(latestRI.data) 
            ? latestRI.data.join('s, ') + 's' 
            : latestRI.data + 's';
        riSummary = `Date: ${latestRI.date} | Suppression Results: ${riVal}`;
    }

    const latestTHI = getLatestLogData('distress_log');
    const lastScore = latestTHI ? `${latestTHI.data}/100` : 'Not Performed';
    const lastTHIDateDisplay = latestTHI ? new Date(latestTHI.date).toLocaleDateString() : 'N/A';
    
    const thoughtRecords = getThoughtRecords();
    const thoughtRecordsCount = thoughtRecords.length;
    let recentThoughtSummary = "N/A";
    if (thoughtRecordsCount > 0) {
        const latest = thoughtRecords[thoughtRecordsCount - 1];
        recentThoughtSummary = `Date: ${new Date(latest.timestamp).toLocaleDateString()}\n`;
        recentThoughtSummary += `  - Situation: ${latest.situation}\n`;
        recentThoughtSummary += `  - Automatic Thought: ${latest.automaticThoughts}\n`;
        recentThoughtSummary += `  - Balanced Thought: ${latest.balancedThought}`;
    }
    const therapyRecs = getTherapyRecommendations();

    return {
        modeName,
        appVersion: APP_VERSION,
        exportDate: new Date().toLocaleString(),
        settings: settingsObj,
        techSpecs: techSpecsObj,
        usage: {
            todayMinutes: Math.round(usage)
        },
        psychological: {
            lastTHIScore: lastScore,
            lastTHIDate: lastTHIDateDisplay,
            thoughtRecordsCount: thoughtRecordsCount,
            recentThoughtSummary: recentThoughtSummary
        },
        recommendations: therapyRecs.status === 'complete' ? therapyRecs.recommendations : [],
        ri: {
            latestRIResult: riSummary
        },
        mml: {
            latestMMLResult: mmlSummary
        },
        lg: {
            latestLGTest: latestLGSummary
        },
        tmc: {
            latestQFactor: latestQFactor
        },
        storage: { usageKB: getLocalStorageUsage() },
        systemStatus: {
            hardwarePhase: validation.phase,
            engineValidation: validation.engine,
            dspValidation: validation.dsp,
            actionableRecommendations: validation.recommendations
        }
    };
}

function generateClinicalReportText(reportData) {
    let text = `TRAHREG TINNITUS THERAPY SUITE - CLINICAL REPORT\n`;
    text += `App Version: ${reportData.appVersion}\n`;
    text += `Therapy Mode: ${reportData.modeName}\n`;
    text += `Export Date: ${reportData.exportDate}\n`;
    text += `-------------------------------------------\n`;
    
    text += `\nTHERAPY SETTINGS:\n`;
    
    if (reportData.aiSummary) {
        text += `\nAI-GENERATED EXECUTIVE SUMMARY:\n`;
        text += `${reportData.aiSummary}\n`;
    }
    for (const [label, value] of Object.entries(reportData.settings)) {
        text += `${label}: ${value}\n`;
    }

    if (Object.keys(reportData.techSpecs).length > 0) {
        text += `\nTECHNICAL SPECIFICATIONS:\n`;
        for (const [label, value] of Object.entries(reportData.techSpecs)) {
            text += `${label}: ${value}\n`;
        }
    }
    
    text += `\nUSAGE & STATUS:\n`;
    text += `Today's Usage: ${reportData.usage.todayMinutes} minutes\n`;

    text += `\nPSYCHOLOGICAL BASELINE (CBT):\n`;
    text += `Last THI Score: ${reportData.psychological.lastTHIScore}\n`;
    text += `Last THI Date: ${reportData.psychological.lastTHIDate}\n`;

    if (reportData.recommendations.length > 0) {
        text += `\nPERSONALIZED THERAPY SUGGESTIONS:\n`;
        reportData.recommendations.forEach(r => {
            text += `- ${r.mode}: ${r.reason}\n`;
        });
    }

    text += `Thought Records Logged: ${reportData.psychological.thoughtRecordsCount}\n`;
    text += `Most Recent Record:\n${reportData.psychological.recentThoughtSummary}\n`;

    text += `\nRESIDUAL INHIBITION (RI):\n`;
    text += `Latest RI Result: ${reportData.ri.latestRIResult}\n`;

    text += `\nMINIMUM MASKING LEVEL (MML):\n`;
    text += `Latest MML Result: ${reportData.mml.latestMMLResult}\n`;

    text += `\nLOUDNESS GROWTH (LG):\n`;
    text += `Latest LG Test: ${reportData.lg.latestLGTest}\n`;

    text += `\nTINNITUS MASKING CURVE (TMC):\n`;
    text += `Latest Q-factor: ${reportData.tmc.latestQFactor}\n`;

    text += `\nSYSTEM STATUS:\n`;
    text += `Hardware Phase Status: ${reportData.systemStatus.hardwarePhase}\n`;
    text += `\nAUTOMATED ENGINE VALIDATION:\n${reportData.systemStatus.engineValidation}\n`;
    
    if (reportData.systemStatus.dspValidation !== 'Not Performed') {
        text += `\nINTERNAL DSP VALIDATION:\nStatus: ${reportData.systemStatus.dspValidation}\n`;
    }

    if (reportData.systemStatus.actionableRecommendations.length > 0) {
        text += `\nACTIONABLE RECOMMENDATIONS:\n${reportData.systemStatus.actionableRecommendations.join('\n')}\n`;
    }

    text += `\n-------------------------------------------`;
    return text.replace(/\r\n/g, '\n').replace(/\n/g, '\r\n');
}

function generateClinicalReportHtml(reportData) {
    let html = `<div style="font-family: 'Segoe UI', sans-serif; color: #333; padding: 20px; max-width: 800px; margin: auto;">`;
    html += `<h1 style="color: #00bfa5; text-align: center;">TRAHREG TINNITUS THERAPY SUITE - CLINICAL REPORT</h1>`;
    html += `<p style="text-align: center; font-size: 0.9em; color: #666;">App Version: ${reportData.appVersion} | Therapy Mode: ${reportData.modeName} | Export Date: ${reportData.exportDate}</p>`;
    html += `<hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">`;

    if (reportData.aiSummary) {
        html += `<h2 style="color: #00bfa5;">AI-GENERATED EXECUTIVE SUMMARY</h2>`;
        html += `<div style="background: #f0f7f4; border: 1px solid #c8e6c9; padding: 15px; border-radius: 8px; margin-bottom: 20px; font-size: 0.95rem;">`;
        html += `<p>${reportData.aiSummary.replace(/\n/g, '<br>')}</p>`;
        html += `</div>`;
    }
    html += `<h2 style="color: #00bfa5;">THERAPY SETTINGS</h2>`;
    html += `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">`;
    for (const [label, value] of Object.entries(reportData.settings)) {
        html += `<tr><td style="padding: 5px 0; border-bottom: 1px dashed #eee; width: 40%;">${label}</td><td style="padding: 5px 0; border-bottom: 1px dashed #eee;">${value}</td></tr>`;
    }
    html += `</table>`;

    if (Object.keys(reportData.techSpecs).length > 0) {
        html += `<h2 style="color: #00bfa5;">TECHNICAL SPECIFICATIONS</h2>`;
        html += `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">`;
        for (const [label, value] of Object.entries(reportData.techSpecs)) {
            html += `<tr><td style="padding: 5px 0; border-bottom: 1px dashed #eee; width: 40%;">${label}</td><td style="padding: 5px 0; border-bottom: 1px dashed #eee;">${value}</td></tr>`;
        }
        html += `</table>`;
    }

    html += `<h2 style="color: #00bfa5;">USAGE & STATUS</h2>`;
    html += `<p><strong>Today's Usage:</strong> ${reportData.usage.todayMinutes} minutes</p>`;

    html += `<h2 style="color: #00bfa5;">PSYCHOLOGICAL BASELINE (CBT)</h2>`;
    html += `<p><strong>Last THI Score:</strong> ${reportData.psychological.lastTHIScore}</p>`;
    html += `<p><strong>Last THI Date:</strong> ${reportData.psychological.lastTHIDate}</p>`;

    if (reportData.recommendations.length > 0) {
        html += `<h3 style="color: #00bfa5;">PERSONALIZED THERAPY SUGGESTIONS</h3>`;
        html += `<ul style="margin-left: 20px; margin-bottom: 10px;">`;
        reportData.recommendations.forEach(r => {
            html += `<li><strong>${r.mode}:</strong> ${r.reason}</li>`;
        });
        html += `</ul>`;
    }

    html += `<p><strong>Thought Records Logged:</strong> ${reportData.psychological.thoughtRecordsCount}</p>`;
    html += `<p><strong>Most Recent Record:</strong><br><pre style="background: #f9f9f9; padding: 10px; border-radius: 5px; white-space: pre-wrap;">${reportData.psychological.recentThoughtSummary}</pre></p>`;

    html += `<h2 style="color: #00bfa5;">RESIDUAL INHIBITION (RI)</h2>`;
    html += `<p><strong>Latest RI Result:</strong> ${reportData.ri.latestRIResult}</p>`;

    html += `<h2 style="color: #00bfa5;">MINIMUM MASKING LEVEL (MML)</h2>`;
    html += `<p><strong>Latest MML Result:</strong> ${reportData.mml.latestMMLResult}</p>`;

    html += `<h2 style="color: #00bfa5;">LOUDNESS GROWTH (LG)</h2>`;
    html += `<p><strong>Latest LG Test:</strong> ${reportData.lg.latestLGTest}</p>`;

    html += `<h2 style="color: #00bfa5;">TINNITUS MASKING CURVE (TMC)</h2>`;
    html += `<p><strong>Latest Q-factor:</strong> ${reportData.tmc.latestQFactor}</p>`;

    html += `<h2 style="color: #00bfa5;">SYSTEM STATUS</h2>`;
    html += `<p><strong>Hardware Phase Status:</strong> ${reportData.systemStatus.hardwarePhase}</p>`;
    html += `<p><strong>Automated Engine Validation:</strong><br><pre style="background: #f9f9f9; padding: 10px; border-radius: 5px; white-space: pre-wrap;">${reportData.systemStatus.engineValidation}</pre></p>`;
    
    if (reportData.systemStatus.dspValidation !== 'Not Performed') {
        html += `<p><strong>Internal DSP Validation:</strong> ${reportData.systemStatus.dspValidation}</p>`;
    }

    if (reportData.systemStatus.actionableRecommendations.length > 0) {
        html += `<h3 style="color: #f44336;">ACTIONABLE RECOMMENDATIONS</h3>`;
        html += `<ul style="margin-left: 20px; color: #f44336;">`;
        reportData.systemStatus.actionableRecommendations.forEach(rec => {
            html += `<li>${rec}</li>`;
        });
        html += `</ul>`;
    }

    html += `<hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">`;
    html += `<p style="text-align: center; font-size: 0.8em; color: #666;">End of Report</p>`;
    html += `</div>`;
    return html;
}

/**
 * Generates personalized therapy recommendations based on THI and MML scores.
 */
function getTherapyRecommendations() {
    const latestTHI = getLatestLogData('distress_log');
    const thiScore = latestTHI ? latestTHI.data : null;

    const latestMML = getLatestLogData('mml_log');
    const lastMMLValue = (latestMML && Array.isArray(latestMML.data)) 
        ? latestMML.data.slice(-1)[0] 
        : (latestMML ? latestMML.data : null);

    if (thiScore === null) {
        return { status: 'incomplete', message: 'Please complete the THI Assessment in CBT & Wellness to get personalized recommendations.' };
    }

    const recs = [];
    const reportsSleepIssues = loadSetting('reports_sleep_issues', 'false') === 'true';

    // Prioritize CBT for High distress
    if (thiScore >= 58) {
        recs.push({
            mode: "CBT & Wellness",
            url: "cbt.html",
            reason: "Your score indicates significant distress. CBT is the clinical gold standard for managing the psychological impact and handicap of tinnitus."
        });
    }

    // Neuromodulation for Moderate/High
    if (thiScore >= 38) {
        recs.push({
            mode: "CR Neuromodulation",
            url: "cr.html",
            reason: "Acoustic Coordinated Reset is designed for moderate-to-severe cases to disrupt synchronized neural firing in the auditory cortex."
        });
        recs.push({
            mode: "Dual-Stimulus",
            url: "lenire.html",
            reason: "Dual-Stimulus pairing (like the Lenire method) can help drive neuroplasticity when simple broadband masking is insufficient."
        });
    } else {
        // Mild cases
        recs.push({
            mode: "Notch Therapy",
            url: "notch.html",
            reason: "Targeted Notch Therapy is ideal for mild-to-moderate tonal tinnitus, encouraging long-term cortical reorganization."
        });
    }

    // Binaural Beats for Sleep or Low Distress
    if (thiScore < 38 || reportsSleepIssues) {
        recs.push({
            mode: "Binaural Beats",
            url: "binaural.html",
            reason: reportsSleepIssues 
                ? "Delta and Theta binaural beats are specifically designed to help transition the brain into deep sleep states and reduce nighttime anxiety."
                : "Since your distress level is low, Binaural Beat entrainment can help maintain relaxation and prevent stress-related spikes."
        });
    }

    // MML specific
    if (lastMMLValue !== null && lastMMLValue > 50) {
        recs.push({
            mode: "Decorrelated Noise",
            url: "decorrelated.html",
            reason: "Since your masking level is high, decorrelated noise can provide effective relief by presenting independent signals to each ear."
        });
    }

    return { status: 'complete', thi: thiScore, mml: lastMMLValue, recommendations: recs };
}

/**
 * Generates a BBCode/Markdown summary of the current setup for community sharing.
 */
function shareSetup(modeName, reportData) {
    const validation = getUnifiedValidationStatus();
    const thi = getLatestLogData('distress_log');
    
    let text = `[b]Trahreg Tinnitus Suite - ${modeName} Setup[/b]\n`;
    text += `[i]Mode: ${modeName}[/i]\n\n`;
    
    for (const [key, val] of Object.entries(reportData)) {
        text += `* ${key}: ${val}\n`;
    }
    
    if (thi) text += `\n[b]Latest THI Score:[/b] ${thi.data}/100 (${new Date(thi.date).toLocaleDateString()})\n`;
    text += `[b]System Validation:[/b] ${validation.isValid ? "Verified" : "Pending"}\n\n`;
    text += `Generated via Trahreg Tinnitus Therapy Suite (v${APP_VERSION})\n`;
    text += `[url]https://github.com/kjgerhart/tinnitus_therapy[/url]`;

    navigator.clipboard.writeText(text).then(() => {
        alert("Setup summary copied to clipboard in BBCode (Tinnitus Talk) and Markdown (Reddit) format. You can now paste it into a forum post!");
    }).catch(err => {
        console.error("Clipboard error:", err);
        alert("Could not copy automatically. Please check the browser console for your share text.");
        console.log(text);
    });
}

/** Global compatibility wrappers */
function initAI() { tinnitusAI.init(); }
async function performGeminiTest() { return await tinnitusAI.performTest(); }
async function fetchAIAssistance(t, p) { return await tinnitusAI.fetchAIAssistance(t, p); }
async function getBalancedThoughtSuggestion(th) { return await tinnitusAI.getBalancedThoughtSuggestion(th); }
async function getSOSSupport(i) { return await tinnitusAI.getSOSSupport(i); }
async function getSoundRecipe(d) { return await tinnitusAI.getSoundRecipe(d); }
async function getPatternAnalysis(q) { return await tinnitusAI.getPatternAnalysis(q); }
async function getTRTExplanation(q) { return await tinnitusAI.getTRTExplanation(q); }
async function getClinicalSummary() { return await tinnitusAI.getClinicalSummary(); }
async function getDailyMotivation() { return await tinnitusAI.getDailyMotivation(); }
async function getEnvironmentalAdvice(db, s) { return await tinnitusAI.getEnvironmentalAdvice(db, s); }
async function getMindfulnessScript(th) { return await tinnitusAI.getMindfulnessScript(th); }
async function getHabituationForecast() { return await tinnitusAI.getHabituationForecast(); }
async function getPersonalizedInsights() { return await tinnitusAI.getPersonalizedInsights(); }

function getRIResults() { return getJson('ri_log', {}); }
function getMMLResults() { return getJson('mml_log', {}); }
function getLoudnessGrowthLog() { return getJson('lg_log', {}); }
function getQFactors() { return getJson('q_factor_log', {}); }
function getTMCLog() { return getJson('tmc_log', {}); }
function clearTMCLog() { localStorage.removeItem('tts_tmc_log'); }

/**
 * Retrieves the date of the most recent Tinnitus Handicap Inventory (THI) assessment.
 * @returns {Date|null} The Date object of the last assessment, or null if none found.
 */
function getLastTHIAssessmentDate() {
    const latest = getLatestLogData('distress_log');
    return latest ? new Date(latest.date) : null;
}

// Initialize the AI manager globally, but only after the DOM is ready
const tinnitusAI = new TinnitusAIManager();

/** Developer Debugging Logs **/
console.log(`[TTS] Persistence Engine v${APP_VERSION} initialized.`);
console.log(`[TTS] AI SDK Detection: ${tinnitusAI._getSDK() ? "✅ Detected" : "❌ Missing"}`);

/**
 * Generic "Video-Style" Walkthrough System
 */
function showWalkthrough(slides, startIndex = 0) {
    let currentSlide = startIndex;
    let autoPlayTimer = null;
    let isAutoPlaying = false;
    let speechSynth = window.speechSynthesis;
    let speechUtterance = null;
    let narratorEnabled = loadSetting('narrator_enabled', 'false') === 'true'; // Load preference
    let narratorSpeed = parseFloat(loadSetting('narrator_speed', '0.9'));
    let narratorVolume = parseFloat(loadSetting('narrator_volume', '1.0'));

    // Ensure only one walkthrough is active at a time
    const existing = document.getElementById('walkthroughModal');
    if (existing) existing.remove();

    document.body.classList.add('tutorial-active');

    const closeWalkthrough = () => { 
        document.body.classList.remove('tutorial-active');
        stopAuto(); 
        clearHighlights(); 
        const el = document.getElementById('walkthroughModal'); 
        if (el) el.remove(); 
    };
    window.closeWalkthrough = closeWalkthrough;

    const clearHighlights = () => {
        document.querySelectorAll('.tutorial-highlight').forEach(el => el.classList.remove('tutorial-highlight'));
    };

    const stopSpeaking = () => {
        if (speechSynth && speechSynth.speaking) {
            speechSynth.cancel();
        }
    };

    const getPlainTextFromHtml = (html) => {
        const tempDiv = document.createElement('div');
        tempDiv.innerHTML = html;
        return tempDiv.textContent || tempDiv.innerText || '';
    };

    const speakContent = (title, contentHtml) => {
        stopSpeaking();
        if (narratorEnabled && speechSynth) {
            const voices = speechSynth.getVoices();
            const textToSpeak = title + ". " + getPlainTextFromHtml(contentHtml);
            speechUtterance = new SpeechSynthesisUtterance(textToSpeak);
            speechUtterance.rate = narratorSpeed;
            speechUtterance.pitch = 1;
            speechUtterance.volume = narratorVolume;

            // Prioritize professional male voices (Neural/Natural/specific professional names)
            const maleKeywords = ['natural', 'neural', 'google us english male', 'microsoft david', 'daniel', 'david', 'alex', 'james', 'male'];
            const selectedVoice = voices
                .filter(v => v.lang.startsWith('en') && maleKeywords.some(k => v.name.toLowerCase().includes(k)))
                .sort((a, b) => {
                    // Prioritize high-quality "Natural" or "Neural" voices for a professional sound
                    const aName = a.name.toLowerCase();
                    const bName = b.name.toLowerCase();
                    const aQuality = aName.includes('natural') || aName.includes('neural');
                    const bQuality = bName.includes('natural') || bName.includes('neural');
                    return bQuality - aQuality;
                })[0];
            
            if (selectedVoice) speechUtterance.voice = selectedVoice;

            // Chained auto-advance: move to next slide after speech ends
            if (isAutoPlaying) {
                speechUtterance.onend = () => {
                    if (isAutoPlaying) {
                        autoPlayTimer = setTimeout(() => {
                            if (currentSlide < slides.length - 1) { currentSlide++; update(); }
                            else stopAuto();
                        }, 1500); // Brief pause after speaking
                    }
                };
            }

            speechSynth.speak(speechUtterance);
        }
    };

    const modalHTML = `
        <div id="walkthroughModal" class="modal-overlay" style="display:block; background: transparent; backdrop-filter: none; pointer-events: none; z-index: 10200;">
            <div id="walkthroughCard" class="modal-card tutorial-mode" style="text-align: center; pointer-events: auto;">
                <div id="wProgress" style="display:flex; gap:5px; margin-bottom:20px; justify-content:center;"></div>
                <h2 id="wTitle" style="color:var(--accent); margin-top:0; font-size: 1.4rem;"></h2>
                <div id="wContent" style="margin: 20px 0; line-height:1.6; min-height:120px; font-size:0.95rem;"></div>
                <div style="display:flex; gap:10px;">
                    <button id="wBack" class="button" style="flex:1;">Back</button>
                    <button id="wNext" class="big-btn play-btn" style="flex:2; margin-top:0;"></button>
                </div>
                <div style="display:flex; justify-content: space-between; align-items: center; margin-top: 15px; flex-wrap: wrap; gap: 10px;">
                    <div style="display:flex; align-items: center; gap: 12px;">
                        <label style="display: flex; align-items: center; gap: 5px; cursor: pointer; font-size: 0.8rem; color: var(--text-dim);">
                            <input type="checkbox" id="narratorToggle" style="width: 16px; height: 16px;">
                            <span>Narrator</span>
                        </label>
                        <label style="display: flex; align-items: center; gap: 5px; font-size: 0.8rem; color: var(--text-dim);">
                            <input type="range" id="narratorSpeed" min="0.5" max="2.0" step="0.1" style="width: 50px; height: 4px; accent-color: var(--accent);">
                            <span id="speedValLabel"></span>
                        </label>
                        <label style="display: flex; align-items: center; gap: 5px; font-size: 0.8rem; color: var(--text-dim);" title="Narrator Volume">
                            <span style="font-size: 0.7rem;">🔊</span>
                            <input type="range" id="narratorVolume" min="0" max="1" step="0.1" style="width: 50px; height: 4px; accent-color: var(--accent);">
                        </label>
                    </div>
                    <div style="display:flex; gap: 5px;">
                        <button id="wAuto" class="button" style="border:none; color:var(--accent); font-size:0.8rem; padding: 5px;">▶ Auto-Play</button>
                        <button onclick="closeWalkthrough()" class="button" style="border:none; color:var(--text-dim); font-size:0.8rem; padding: 5px;">Close Guide</button>
                    </div>
                </div>
            </div>
        </div>
    `;
    document.body.insertAdjacentHTML('beforeend', modalHTML);

    try {
        // Set initial state of narrator toggle
        document.getElementById('narratorToggle').checked = narratorEnabled;
        document.getElementById('narratorToggle').onchange = (e) => {
            narratorEnabled = e.target.checked;
            saveSetting('narrator_enabled', narratorEnabled);
            if (!narratorEnabled) stopSpeaking(); 
        };

        // Set initial state of speed slider
        const speedSlider = document.getElementById('narratorSpeed');
        const speedLabel = document.getElementById('speedValLabel');
        speedSlider.value = narratorSpeed;
        speedLabel.textContent = narratorSpeed.toFixed(1) + 'x';
        speedSlider.oninput = (e) => {
            narratorSpeed = parseFloat(e.target.value);
            speedLabel.textContent = narratorSpeed.toFixed(1) + 'x';
            saveSetting('narrator_speed', narratorSpeed);
        };

        // Set initial state of volume slider
        const volumeSlider = document.getElementById('narratorVolume');
        volumeSlider.value = narratorVolume;
        volumeSlider.oninput = (e) => {
            narratorVolume = parseFloat(e.target.value);
            saveSetting('narrator_volume', narratorVolume);
        };
    } catch (err) {
        console.warn("Tutorial UI failed to initialize:", err);
        closeWalkthrough();
        return;
    }

    const stopAuto = () => { // This function also stops speaking
        if (autoPlayTimer) {
            clearTimeout(autoPlayTimer);
            autoPlayTimer = null;
        }
        isAutoPlaying = false;
        document.getElementById('wAuto').textContent = "▶ Auto-Play";
        stopSpeaking();
    };

    const update = () => {
        if (!slides || !slides[currentSlide]) return closeWalkthrough();
        
        clearHighlights();
        const s = slides[currentSlide];
        if (document.getElementById('wTitle')) document.getElementById('wTitle').textContent = s.title;
        document.getElementById('wContent').innerHTML = s.content;
        document.getElementById('wNext').textContent = currentSlide === slides.length - 1 ? "Finish" : "Next";
        document.getElementById('wBack').style.visibility = currentSlide > 0 ? 'visible' : 'hidden';
        document.getElementById('wProgress').innerHTML = slides.map((_, i) => `<div style="width:20px; height:4px; border-radius:2px; background:${i <= currentSlide ? 'var(--accent)' : 'var(--surface)'}"></div>`).join('');

        if (s.selector) {
            const target = document.querySelector(s.selector);
            if (target) {
                target.scrollIntoView({ behavior: 'smooth', block: 'center' });
                target.classList.add('tutorial-highlight');
            }
        }

        // Speak content if auto-playing and narrator is enabled
        if (narratorEnabled) {
            speakContent(s.title, s.content);
        } else {
            stopSpeaking(); // Ensure speech stops if not auto-playing or narrator disabled
            // If auto-playing but narrator is off, we need a standard timer to advance
            if (isAutoPlaying) {
                autoPlayTimer = setTimeout(() => {
                    if (currentSlide < slides.length - 1) { currentSlide++; update(); }
                    else stopAuto();
                }, 7000); // Standard slide duration
            }
        }
    };

    document.getElementById('wNext').onclick = () => { 
        stopAuto();
        if (currentSlide < slides.length - 1) { currentSlide++; update(); } 
        else closeWalkthrough(); 
    };
    document.getElementById('wBack').onclick = () => { stopAuto(); if (currentSlide > 0) { currentSlide--; update(); } };
    
    document.getElementById('wAuto').onclick = () => {
        if (isAutoPlaying) {
            stopAuto();
        } else {
            isAutoPlaying = true;
            document.getElementById('wAuto').textContent = "⏸ Paused";
            update();
        }
    };

    update();
}

/**
 * Displays a summary of updates for the current version.
 */
function showWhatsNew() {
    showWalkthrough([
        { title: "Version 2.2.9 - What's New", content: "This update resolves a critical syntax error in the persistence engine and improves AI SDK stability." },
        { title: "Modular Architecture", content: "Data and AI management have been refactored into dedicated modules, improving reliability and stability across the entire suite." },
        { title: "Performance Profiling", content: "A new Performance Monitor has been added to track audio engine health, ensuring your therapeutic signals are always accurate." },
        { title: "Security Hardening", content: "Your API keys are now protected with high-grade AES-GCM encryption. We've also added security sanitization to our Python tools." },
        { title: "Enhanced Reports", content: "Clinical reports now feature deeper data integration and AI-generated progress summaries, making it easier to share results with your clinician." }
    ]);
}

function showQuickStartGuide() {
    showWalkthrough([
        { title: "Welcome to Relief", content: "Tinnitus management is a journey of training the brain. This suite provides the tools research shows are most effective for 'habituation'." },
        { title: "The Golden Rule: Mixing", content: "<b>Important:</b> Do not hide your tinnitus completely. Set your therapy volume so the sound and your tinnitus 'mix'. Your brain needs to hear both to learn the tinnitus is neutral." },
        { title: "Step 1: Calibration", content: "Visit the <b>Notch Finder</b> first. You must find your exact tinnitus pitch so therapies can target the correct neural clusters." },
        { title: "Step 2: Passive Listening", content: "Use therapy for 30–60 minutes daily. Don't focus on it—let it be background 'wallpaper' while you work or relax." },
        { title: "Step 3: Reports & AI", content: "Review your progress monthly using the <b>Clinical Report</b>. If you feel stuck, use the <b>AI Insights</b> tool to identify patterns and triggers." }
    ]);
}

/**
 * Starts a module-specific tutorial walkthrough.
 */
function startModuleTutorial(key, startIndex = 0) {
    const tutorials = {
        'decorrelated': [
            { title: "Hardware Check", content: "Plug in your headphones. This therapy depends on your brain receiving two different, independent signals.", selector: "h1" },
            { title: "Sound Source", content: "Select your preferred noise color or nature sound. Pink noise is often most comfortable for long sessions.", selector: "#color" },
            { title: "EQ Setup", content: "Use the EQ sliders to boost frequencies where you have hearing loss. This reduces the 'listening effort' required by your brain.", selector: "#eqSection" },
            { title: "The Mixing Point", content: "Adjust the volume so the noise and your tinnitus 'mix'. Do not mask the sound completely.", selector: "#volMaster" },
            { title: "Start Session", content: "Set your timer and begin your daily therapy session.", selector: "#toggleBtn" },
            { title: "Share Your Setup", content: "Found a configuration that provides relief? Share it with the community to help others find their mixing point.", selector: "button[onclick='shareToCommunity()']" }
        ],
        'notch': [
            { title: "Pitch Match", content: "Use the test tone to find your exact tinnitus pitch. Precision is critical for effective Notch therapy.", selector: "#step1Section" },
            { title: "Set the Notch", content: "Input your matched frequency here. This 'silences' the noise in that specific frequency range.", selector: "#step2Section" },
            { title: "Notch Width", content: "Set the width to 1.0 octaves (clinical standard). This determines the size of the 'hole' in the noise.", selector: "#step2Section" },
            { title: "Volume Mix", content: "Adjust volume to the mixing point. You should still hear your tinnitus inside the notch.", selector: "#volMaster" },
            { title: "Start Therapy", content: "Activate the engine to begin the cortical reorganization process.", selector: "#toggleBtn" },
            { title: "Share Your Setup", content: "Sharing your matched frequency and volume levels helps others understand how to calibrate their own notch therapy.", selector: "button[onclick='shareToCommunity()']" }
        ],
        'cr': [
            { title: "Precise Bracketing", content: "Use this tone to exactly match your tinnitus pitch. This determines the 4 therapeutic frequencies.", selector: ".card:first-of-type" },
            { title: "Tone Calculation", content: "Once matched, click here to calculate your personalized therapy sequence.", selector: "#baseFreq" },
            { title: "Perceived Loudness", content: "Adjust these sliders until all four tones sound equally loud to you. Balance is vital for success.", selector: ".bal-slider-row" },
            { title: "Volume & Timing", content: "Set your session time (60 mins recommended) and start the coordinated reset sequence.", selector: "#toggleBtn" },
            { title: "Share Your Setup", content: "Acoustic CR is complex; sharing your bracketing results can help the community refine their own sequences.", selector: "button[onclick='shareToCommunity()']" }
        ],
        'lenire': [
            { title: "Neuromodulation", content: "This engine uses bursts and modulated noise to drive auditory neuroplasticity.", selector: "h1" },
            { title: "Visual Sync", content: "Enable the visual pulse to add multisensory input, which can enhance the therapeutic effect.", selector: "#visualPulse" },
            { title: "Tactile Bimodal Setup", content: "If using a smartphone, enable Haptic Pulse. The phone will vibrate in sync with the sound bursts, providing a safe, tactile 'second sense' to help your brain re-focus away from tinnitus.", selector: "#hapticPulse" },
            { title: "Intensity Control", content: "Adjust the Vibration Intensity to find a level that is noticeable but not distracting. A gentle tap synchronized with the sound is usually most effective.", selector: "#hapticStrengthCtrl" },
            { title: "Trigger Calibration", content: "Adjust Trigger Sensitivity until the device pulses only when you hear a tone burst. If it vibrates constantly, increase the value. If it misses bursts, decrease it.", selector: "#hapticSensCtrl" },
            { title: "Dual-Mode Connection", content: "Pair your Finger Pacer via **Bluetooth** for wireless use, or **USB** for the highest reliability. USB mode is fully supported on Android phones using an OTG adapter.", selector: "#connectBleBtn" },
            { title: "3D Design Preview", content: "You can view the professional, ergonomic mount design here. This model helps during fitting and user testing.", selector: "button[onclick='toggle3DPreview()']" },
            { title: "Auditory Pacer", content: "Enable Auditory Cues to hear a subtle chime at the start of each breath. This allows you to maintain synchronization even with your eyes closed.", selector: "#pacerAudio" },
            { title: "Pulse Rate", content: "Adjust the pulse speed to match your natural resting breath. A slow, steady rhythm (around 5-6 breaths per minute) is usually best for relaxation.", selector: "#pulseRate" },
            { title: "Breathing Sync", content: "Try to match your breathing to the visual pulse. Inhaling as the light expands and exhaling as it fades helps activate the body's relaxation response, further aiding habituation.", selector: "#visualPulse" },
            { title: "The Mix", content: "Balance the tones and noise so neither is overwhelming. The sound should shimmer background.", selector: "#mixL" },
            { title: "Zen Mode", content: "Once your settings are dialed in, use Zen Mode to hide technical controls. This encourages 'Passive Listening'—allowing the sound to become background wallpaper while you focus on other tasks.", selector: "#zenBtn" },
            { title: "Help the Community", content: "Found a setup that works for you? Use the 'Share Setup' button to generate a summary you can post on forums like Tinnitus Talk or Reddit. Helping others find relief is the best way to grow this project!", selector: "button[onclick='shareToCommunity()']" }
        ],
        'soundtherapy': [
            { title: "Sound Types", content: "Choose between calibrated broadband noise for habituation or nature sounds for relaxation.", selector: ".btn-grid:first-of-type" },
            { title: "Breathing Pacer", content: "Use the 4-7-8 pacer to lower physiological stress during a tinnitus spike.", selector: "#pacerToggle" },
            { title: "Volume Calibration", content: "Set to the 'Mixing Point'. If you hide the tinnitus completely, you aren't habituating.", selector: "#volume" },
            { title: "Sleep Support", content: "Enable Sleep Fade for a soft 60-second shutdown when the timer ends.", selector: "#sleepMode" },
            { title: "Share Your Setup", content: "Share your favorite soundscapes and masking levels with the community.", selector: "button[onclick='shareToCommunity()']" }
        ],
        'notchfinder': [
            { title: "Frequency Input", content: "Adjust the pitch using the slider or type a value. This identifies your tinnitus 'center frequency'.", selector: ".responsive-grid" },
            { title: "Auto-Sweep", content: "Use this to slowly climb the frequency range. It's often easier to find the match while the sound is moving.", selector: "#speedSlider" },
            { title: "Test & Listen", content: "Toggle the tones to compare the external sound against your internal tinnitus.", selector: "#playBtn" },
            { title: "Save Settings", content: "Once matched, save here. This frequency will be used across all other therapy modules automatically.", selector: "#saveBtn" },
            { title: "Matching Difficulty?", content: "If you cannot find a match, you may have hearing loss in that frequency region. Use the <b>Hearing Test</b> tool to check your audibility levels.", selector: "h1" }
        ],
        'tmc': [
            { title: "Point Calibration", content: "For each frequency, find the 'Minimum Masking Level'—the quietest volume that just hides your tinnitus.", selector: "#freqSlider" },
            { title: "Mapping the Curve", content: "Save multiple points across the spectrum to visualize your auditory filter shape.", selector: "button[onclick='savePoint()']" },
            { title: "Tuning Analysis", content: "The Q-factor indicates how 'sharp' your tinnitus signal is. A higher number suggests a more tonal perception.", selector: "#tmcChart" }
        ],
        'lg': [
            { title: "Objective vs Subjective", content: "Play a tone and increase the volume. We are measuring how your brain perceives loudness growth.", selector: "#volSlider" },
            { title: "Rating Scale", content: "Rate the sound from 'Very Soft' to 'Uncomfortable'. This helps identify hyperacusis (loudness sensitivity).", selector: ".btn-grid" },
            { title: "The Curve", content: "A steep line on this chart can indicate the presence of recruitment or hyperacusis.", selector: "canvas" }
        ],
        'ri': [
            { title: "Suppression Setup", content: "Choose a noise color. We will play this for 60 seconds at a level that completely hides your tinnitus.", selector: "#noiseColor" },
            { title: "The Stopwatch", content: "After the noise stops, time how long it takes for your tinnitus to return to its normal level.", selector: "#step3" },
            { title: "History", content: "Track your RI duration over time. Longer suppression periods are a positive clinical sign.", selector: "#riHistory" }
        ],
        'validation': [
            { title: "Phase Verification", content: "This is critical. Ensure the 'In-Phase' tone sounds centered in your head, not 'wide' or hollow.", selector: ".card" },
            { title: "Engine Check", content: "Run the automated tests to verify the suite's DSP engine is producing accurate clinical signals.", selector: ".play-btn" },
            { title: "Results Log", content: "View technical details like filter attenuation and stereo separation here.", selector: "#results" }
        ],
        'twotone': [
            { title: "Bracketing", content: "Compare Tone A and Tone B to 'bracket' your tinnitus. This helps avoid octave-match errors.", selector: ".card:first-of-type" },
            { title: "Saving", content: "If one tone is a perfect match, save it directly to your global settings.", selector: "button[onclick*='saveToNotch']" }
        ],
        'sweep': [
            { title: "Range Test", content: "This sweep moves from 20Hz to 20kHz. It helps identify 'dead zones' or frequency triggers.", selector: "h2" },
            { title: "Volume Safety", content: "Always start at a low volume (10% or less) before beginning a high-frequency sweep.", selector: "#volSlider" }
        ],
        'hearingtest': [
            { title: "Exploration", content: "Tap each button to check your audibility thresholds across the spectrum.", selector: ".section-title" },
            { title: "Clinical Note", content: "Remember: This is an exploration tool, not a replacement for a professional audiogram.", selector: "p" }
        ]
    };

    if (tutorials[key]) {
        showWalkthrough(tutorials[key], startIndex);
    } else {
        showQuickStartGuide();
    }
}

function applyCompactMode() {
    const isCompact = loadSetting('compact_mode', 'false') === 'true';
    document.documentElement.classList.toggle('compact-mode', isCompact);
}

function toggleCompactMode() {
    const isCompact = loadSetting('compact_mode', 'false') === 'true';
    saveSetting('compact_mode', isCompact ? 'false' : 'true');
    applyCompactMode();
}
window.toggleCompactMode = toggleCompactMode;

function applyDashboardLayout() {
    const layout = loadSetting('dashboard_layout', '2-column');
    document.documentElement.classList.toggle('single-column-layout', layout === '1-column');
}

function toggleDashboardLayout() {
    const current = loadSetting('dashboard_layout', '2-column');
    const next = current === '2-column' ? '1-column' : '2-column';
    saveSetting('dashboard_layout', next);
    applyDashboardLayout();
}
window.toggleDashboardLayout = toggleDashboardLayout;

function applyTheme() {
    const theme = loadSetting('theme', 'dark');
    document.documentElement.classList.toggle('light-mode', theme === 'light');
    if (document.body) {
        document.body.classList.toggle('light-mode', theme === 'light');
    }
}

function applyEmailVisibility() {
    const email = loadSetting('audiologist_email', '');
    const isValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    document.querySelectorAll('.email-audiologist-btn').forEach(btn => {
        btn.classList.toggle('hidden', !isValid);
    });
}

function toggleTheme() {
    const theme = loadSetting('theme', 'dark');
    const next = theme === 'dark' ? 'light' : 'dark';
    saveSetting('theme', next);
    applyTheme();
}
window.toggleTheme = toggleTheme;

function syncUIVersion() {
    document.querySelectorAll('.app-version-label').forEach(el => {
        const prefix = el.dataset.versionPrefix || '';
        const suffix = el.dataset.versionSuffix || '';
        el.textContent = `${prefix}${APP_VERSION}${suffix}`;
    });
}

// Immediate application to prevent flash of unstyled content
(function() {
    const theme = localStorage.getItem('tts_theme');
    if (theme === 'light') {
        document.documentElement.classList.add('light-mode');
    }
    
    const compact = localStorage.getItem('tts_compact_mode');
    if (compact === 'true') {
        document.documentElement.classList.add('compact-mode');
    }
    
    const layout = localStorage.getItem('tts_dashboard_layout');
    if (layout === '1-column') {
        document.documentElement.classList.add('single-column-layout');
    }
    
    // --- Trahreg Gatekeeper Logic ---
    (async function() {
        const fullPath = decodeURIComponent(window.location.pathname).toLowerCase();
        const pageName = fullPath.split('/').pop();
        const isDocs = fullPath.includes('/docs/');

        // Remote Maintenance Toggle: Check for a maintenance.json file to allow remote control
        try {
            const configPath = isDocs ? '../maintenance.json' : 'maintenance.json';
            const response = await fetch(configPath, { cache: 'no-store' });
            if (response.ok) {
                const config = await response.json();
                if (config && typeof config.enabled === 'boolean') {
                    MAINTENANCE_MODE = config.enabled;
                }
            }
        } catch (e) { /* Fallback to hardcoded MAINTENANCE_MODE on network error */ }

        // Maintenance Mode Redirect
        if (MAINTENANCE_MODE && pageName !== 'maintenance.html') {
            console.warn("[Gatekeeper] Suite is down for maintenance.");
            window.location.replace(isDocs ? '../maintenance.html' : 'maintenance.html');
            return;
        }

        // 1. Identify Home/Root and authorize the session (more robust detection)
        // Check if the path ends with common root patterns or project directory name
        const homePatterns = ['index.html', '', 'tinnitus_therapy', 'tinnitus_therapy/'];
        const isHome = homePatterns.some(p => pageName === p || fullPath.endsWith(p));

        try {
            // Set session active if we are on the home page or a public page to avoid immediate redirect
            if (isHome || isDocs) _memSessionActive = true;
        } catch(e) { /* Private mode protection */ }

        // 2. Identify Whitelisted (Public) pages
        const publicPages = ['index.html', 'disclaimer.html', 'license.html', 'about.html', 'research.html', 'feedback.html', 'presentation.html', 'handout.html', 'clinical_summary.html', 'stats.html'];
        const isPublicPage = isHome || publicPages.some(p => pageName === p);

        const onboardingStep = parseInt(loadSetting('onboarding_step', '0'));
        const sessionActive = _memSessionActive || (function() {
            try { return sessionStorage.getItem('tts_session_active') === 'true'; } 
            catch(e) { return false; }
        })();

        if (!isStorageAvailable()) {
            console.error("[Gatekeeper] LocalStorage is blocked. The suite cannot save your progress.");
            alert("Warning: Your browser is blocking LocalStorage. Therapy settings and progress will not be saved.");
        }

        // 3. Enforce Redirection: Bypass if already onboarded OR session is active
        if (!isPublicPage && onboardingStep < 1 && !sessionActive) {
            console.warn("[Gatekeeper] Disclaimer acceptance required. Redirecting to home...");
            const redirectTarget = isDocs ? '../index.html' : 'index.html';
            window.location.replace(redirectTarget);
        }
    })();
})();

// Re-sync with body once DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
        applyTheme();
        applyCompactMode();
        applyDashboardLayout();
        applyEmailVisibility();
        syncUIVersion();

        // Version Update Notification
        const onboardingStep = parseInt(localStorage.getItem('tts_onboarding_step') || '0');
        const lastSeenVersion = localStorage.getItem('tts_last_seen_version');
        // Only trigger "What's New" if user has completed onboarding to avoid UI conflicts
        if (onboardingStep >= 7 && lastSeenVersion && lastSeenVersion !== APP_VERSION) {
            setTimeout(showWhatsNew, 1500);
        }
        if (onboardingStep >= 7) localStorage.setItem('tts_last_seen_version', APP_VERSION);
    });
} else {
    applyTheme();
    applyCompactMode();
    applyDashboardLayout();
    applyEmailVisibility();
    syncUIVersion();

    // Version Update Notification
    const onboardingStep = parseInt(localStorage.getItem('tts_onboarding_step') || '0');
    const lastSeenVersion = localStorage.getItem('tts_last_seen_version');
    if (onboardingStep >= 7 && lastSeenVersion && lastSeenVersion !== APP_VERSION) {
        setTimeout(showWhatsNew, 1500);
    }
    if (onboardingStep >= 7) localStorage.setItem('tts_last_seen_version', APP_VERSION);
}

function needsValidation() {
    return !getUnifiedValidationStatus().isValid;
}
